remote_theme: tuur29/pages-themes-cayman
title: ICRA 2025 Workshop on Resilient Off-road Autonomus Robotics (ICRA-ROAR 2025)
color:
  gradient_left: "#4b5320" 
  gradient_right: "#4b5320"
  header: "#e8e3e3"
  android_theme: "#000" # this default to gradient_color
  link: "#1e6bb8" # this default to gradient_color
  section_title: "#159957" # this default to gradient_color

syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

github: 
  is_project_page: false

author: # (c) https://sites.google.com/view/guillermogallego
  name: Shubhra Aich

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/organizers/wenshan.png
        height: 480
        width: 640
